all:
  hosts:
    localhost:
    # Current server (localhost) - runs as current user, creates deploy user
      ansible_connection: local
    
    # Add remote servers here:
    # production-server:
    #   ansible_host: your-server-ip
    #   ansible_user: deploy
    #   ansible_ssh_private_key_file: ~/.ssh/id_rsa
    #   ansible_port: 2222

  vars:
    # User Configuration
    deploy_user: deploy          # New user to create
    deploy_user_shell: /bin/bash

    # Server Configuration
    server_hostname: feedback-server
    server_timezone: UTC
       
    # Application Configuration
    app_name: feedback-app
    app_domain: yourdomain.com
    app_port: 3000
    
    # Database Configuration
    db_name: "{{ app_name }}"
    db_user: dbuser
    db_password: changeme_secure_password
    
