# Application Setup Tasks

---
- name: Create application directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0755'
  with_items:
    - "/home/{{ deploy_user }}/apps/{{ app_name }}"
    - "/home/{{ deploy_user }}/apps/{{ app_name }}/data"
    - "/home/{{ deploy_user }}/apps/{{ app_name }}/logs"
    - "/home/{{ deploy_user }}/apps/{{ app_name }}/config"
    - "/home/{{ deploy_user }}/apps/{{ app_name }}/backups"
  tags: [application]

- name: Set proper ownership for entire app directory
  file:
    path: "/home/{{ deploy_user }}/apps/{{ app_name }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes
  tags: [application]
