# Docker Installation Tasks

---
- name: Remove old Docker versions and clean repositories
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-doc
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes
  tags: [docker]

- name: Clean up existing Docker repositories and keys
  shell: |
    # Remove all Docker repository files
    rm -f /etc/apt/sources.list.d/docker*.list
    rm -f /etc/apt/sources.list.d/*docker*
    
    # Remove all Docker GPG keys
    rm -f /usr/share/keyrings/docker*.gpg
    rm -f /etc/apt/keyrings/docker*.gpg
    rm -f /usr/share/keyrings/docker-archive-keyring.gpg
    
    # Clean apt cache
    apt-get clean
    
    echo "Docker repositories cleaned"
  tags: [docker]

- name: Update apt to clear old repository cache
  apt:
    update_cache: yes
    force_apt_get: yes
  tags: [docker]

- name: Install Docker prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  tags: [docker]

- name: Create directory for Docker GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags: [docker]

- name: Add Docker's official GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  tags: [docker]

- name: Add Docker repository (official method)
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  tags: [docker]

- name: Update apt package index after adding Docker repository
  apt:
    update_cache: yes
    force_apt_get: yes
  tags: [docker]

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: [docker]

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: [docker]

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ deploy_user }}"
    - "{{ current_user }}"
  tags: [docker]

- name: Install Docker Compose standalone
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.0/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  tags: [docker]

- name: Test Docker installation
  shell: docker run --rm hello-world
  register: docker_test
  become_user: "{{ current_user }}"
  retries: 3
  delay: 5
  until: docker_test.rc == 0
  ignore_errors: yes
  tags: [docker]