# Security Configuration Tasks

---
# SSH Configuration (disabled by default for safety)
- name: Backup original SSH config
  copy:
    src: /etc/ssh/sshd_config
    dest: "/etc/ssh/sshd_config.backup.{{ ansible_date_time.epoch }}"
    remote_src: yes
  tags: [security, ssh]

- name: Display SSH hardening warning
  debug:
    msg: |
      SSH HARDENING DISABLED FOR SAFETY
      
      SSH hardening is disabled by default to prevent lockouts.
      
      To enable SSH hardening:
      1. Ensure you have SSH key access working
      2. Test that you can SSH as both {{ current_user }} and {{ deploy_user }}
      3. Run with: ansible-playbook ... --extra-vars "enable_ssh_hardening=true"
  tags: [security, ssh]
  when: not (enable_ssh_hardening | default(false))

# Firewall Configuration
- name: Reset UFW to defaults
  ufw:
    state: reset
  tags: [security, firewall]

- name: Set UFW default policies
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }
  tags: [security, firewall]

- name: Configure UFW rules (preserve current SSH port)
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    comment: "{{ item.comment | default('') }}"
  with_items:
    - { port: "22", comment: "SSH (original port)" }
    - { port: "{{ ssh_port }}", comment: "SSH (custom)" }
    - { port: "80", comment: "HTTP" }
    - { port: "443", comment: "HTTPS" }
    - { port: "{{ app_port }}", comment: "Application" }
  tags: [security, firewall]

- name: Enable UFW
  ufw:
    state: enabled
  tags: [security, firewall]

# Fail2ban Configuration
- name: Configure fail2ban jail
  copy:
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = 22,{{ ssh_port }}
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3
      
      [nginx-http-auth]
      enabled = false
      
      [nginx-limit-req]
      enabled = false
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban
  tags: [security, fail2ban]

- name: Start and enable fail2ban
  systemd:
    name: fail2ban
    state: started
    enabled: yes
  tags: [security, fail2ban]

# Handlers
- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted